### ISSUE TITLE
Angular 9 

### ISSUE THREAD

**Issue by takhil** [moribvndvs/ng2-idle#137]
------
npm WARN @ng-idle/core@8.0.0-beta.4 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-idle/core@8.0.0-beta.4 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-idle/keepalive@8.0.0-beta.4 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-idle/keepalive@8.0.0-beta.4 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
-------
I'm seeing above warnings when i do "npm update" 

Angular version 9.02
node : 12.3
npm : 6.0

Will. there be any issues with these warnings did any one facing issues ?

**Comment by scottfrenzy** [comment]
I haven't faced any issues yet using angular 9. All seems to be working for me (using idle and keepalive)

**Comment by sudhakar-sekar** [comment]
Hi,

I am also facing the same issue.

Angular : v9.1.4
NodeJS : 12.16.3
NPM : 6.14.4

When we will expect the Angular 9 support?

Thanks,
Sudhakar Chandrasekaran.

**Comment by iompo** [comment]
Hi guys, 
I did update the modules _core_ and _keep-alive_ to angular 9.1.6. Who should I ask to be able to propose a pull request?

Marco.

**Comment by scottfrenzy** [comment]
> I did update the modules _core_ and _keep-alive_ to angular 9.1.6. Who should I ask to be able to propose a pull request?
Thanks for doing this! Check out the **Submitting a Pull Request** section [here](https://github.com/moribvndvs/ng2-idle/blob/master/CONTRIBUTING.md)

**Comment by moribvndvs** [comment]
Addressed in #141
