### ISSUE TITLE
Not supporting Angular 9.1 

### ISSUE THREAD

**Issue by abhijatyatewari** [moribvndvs/ng2-idle#138]
node_modules/@ng-idle/keepalive/lib/keepalive.d.ts:25:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 
type argument(s).

25     static ɵfac: ɵngcc0.ɵɵFactoryDef<Keepalive>;

**Comment by moribvndvs** [comment]
Addressed in #141
