### ISSUE TITLE
Update the keep-alive peer dependency on ng-idle/core 

### ISSUE THREAD

**Issue by raulcrisan** [moribvndvs/ng2-idle#145]
**Describe the bug**
When you try to install the **ng-idle/keepalive@10.0.0-beta.1** the npm throws a warning that keepalive has a dependency of ng-idle/core version 10.0.0 but none was found.

**ng-idle/core** has the right version **10.0.0-beta.1**, and the issue is that somehow the **postrelease.js** script removed the right version from **lerna** file and put it the wrong version **10.0.0**.

Also the release tag is wrong.

**To Reproduce**
Run this command **npm install -s @ng-idle/core@10.0.0-beta.1 @ng-idle/keepalive@10.0.0-beta.1**

**Expected behavior**
No warnings should be displayed after installing ng2-idle projects

**Comment by patrickrioux** [comment]
Please fix the dependency to remove the build warning. Thanks.

**Comment by erikramalho** [comment]
please fix this

**Comment by jtth** [comment]
Please fix this.

**Comment by alongouldman** [comment]
is this being fixed?

**Comment by moribvndvs** [comment]
11.0.3 has been released, I found an issue in the publish process. This release should allow angular 9 - 12 so I think you can skip 10 altogether.
