### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by diegocloudstorm** [moribvndvs/ng2-idle#148]
Any plans of upgrading the plugin to support Angular 11?

**Comment by erikramalho** [comment]
Please, suport it! ❤️

**Comment by NateRadebaugh** [comment]
Is there something unique to this implementation that requires angular 10.x?

**Comment by alongouldman** [comment]
did someone find any workarounds for this issue?

**Comment by plamendp** [comment]
I've just upgraded Angular from 10 to 11. 

"npm install" warns me about the broken requirement, but application works nonetheless (keep alive, pings, etc.).

However, yes, would be nice to have dependency updated.

**Comment by NateRadebaugh** [comment]
Is this PR enough to resolve this, or is there more work needed?  What can we do to get this completed?
#151

**Comment by pmcelreavy** [comment]
The project is looking for a maintainer though. I don't know if the current maintainer has much time to even look at the issues.

**Comment by NehaTawar** [comment]
Any updates on upgrading the plugin to support  latest Angular 12+?
Getting a error of incompatibility with @angular/common. Have to force install the node_modules. Please let us know.

**Comment by NateRadebaugh** [comment]
Seems these issues are ignored. After all this time may make sense to fork this repo and release a separate package.

**Comment by erikramalho** [comment]
Hey @NateRadebaugh why don’t you fork it and we all can use your fork? You’re right. This repo seems to be dead at all… we all coul maintain it

**Comment by moribvndvs** [comment]
#97 is a pinned topic about needing a new maintainer if you want to get involved. I'll also accept a pull request for Angular 11 support. Someone is working on 12.

**Comment by NateRadebaugh** [comment]
Thanks @moribvndvs  we'll track next steps with @worksoncloud  since it looks like he's the newly appointed maintainer.

**Comment by moribvndvs** [comment]
#151 has been merged and this has all been released as 11.0.3
