### ISSUE TITLE
Support for Angular 12+?

### ISSUE THREAD

**Issue by NehaTawar** [moribvndvs/ng2-idle#155]
Any plan on upgrading the module to support latest Angular 12+? 
Getting a error of incompatibility with @angular/common. Have to force install the node_modules.

**Comment by NateRadebaugh** [comment]
Support for Angular 12 is being tracked in the following PR: #151

**Comment by moribvndvs** [comment]
#151 has been merged and @ng-idle/core and @ng-idle/keepalive have been published. I had some problems with bugs in the publishing side of things, use 11.0.3 to be sure.
