### ISSUE TITLE
Update to Angular 13's new package format and compile with partial-ivy

### ISSUE THREAD

**Issue by xylplm** [moribvndvs/ng2-idle#165]
With Angular 13 a new package format was rolled out. They're also encouraging library developers to publish libraries with partial ivy compilation mode, which removes the need for ngcc. This library is not being published with either partial-ivy or the new package format.

`Processing legacy "View Engine" libraries:
- @ng-idle/core [es2015/esm2015] (git+https://github.com/moribvndvs/ng2-idle.git)
- @ng-idle/keepalive [es2015/esm2015] (git+https://github.com/moribvndvs/ng2-idle.git)
Encourage the library authors to publish an Ivy distribution.`

If you use ngpackagr and Angular 13 to build the library, then this should be solved naturally. If not, here are the details about the new package format: https://angular.io/guide/angular-package-format

**Comment by WuglyakBolgoink** [comment]
any update on this issue? now we have angular@14...

**Comment by HarelM** [comment]
Would be nice to have this warning removed, any info on that?
Is there still a maintenance issue (as I've seen a lot of people volunteering to help maintain this package)?

**Comment by HarelM** [comment]
Would be nice to have this warning removed, any info on that?
Is there still a maintenance issue (as I've seen a lot of people volunteering to help maintain this package)?

**Comment by moribvndvs** [comment]
I accept pull requests. I don't have bandwidth for this right now, I hate to say.

As for a help maintaining, I've had people stop by to help but they don't tend to stick around for unknown reasons.

**Comment by HarelM** [comment]
Ok, thanks for the quick response! 
I'll see what I can do in terms of PR for this.
If anyone in this thread want to beat me to it feel free :-)

**Comment by HarelM** [comment]
I've opened the following PR:
https://github.com/moribvndvs/ng2-idle/pull/169
Besides running the tests is there another way to make sure everything is as expected?
