### ISSUE TITLE
Release version 12

### ISSUE THREAD

**Issue by HarelM** [moribvndvs/ng2-idle#183]
There was a pull request that was merged and a tag was created, the changelog was updated but there's no new package in npm.
https://www.npmjs.com/package/@ng-idle/core
Is there anything I can do to push this forward?

**Comment by dotdotcommadot** [comment]
I assume this means this project should not be relied upon anymore?

**Comment by HarelM** [comment]
Would be nice to be able to push new releases and allow merging of pull requests.

**Comment by NatanCoralogix** [comment]
any updates on this?

**Comment by un1c0rnr1d3r** [comment]
@NatanCoralogix I posted a couple of PRs for the updates to Angular 14 and 15. Will try to put together one more for Angular v16. Unfortunately, I don't think I have permissions to publish releases to npm.

**Comment by NatanCoralogix** [comment]
@un1c0rnr1d3r 
Thanks, Did u consider to fork and own the new package?
