### ISSUE TITLE
Add support for Angular 16

### ISSUE THREAD

**Issue by dsubelman** [moribvndvs/ng2-idle#187]
### **Desired functionality**

Add support for Angular 16 release.

Now that Angular 16 has been released, are there any plans to release a new version that supports Angular 16?

**Comment by vc-jaydeep** [comment]
And also how to use with standalone component

**Comment by Ross-Blakeney** [comment]
Since the ngcc was dropped in angular 16, this is a hard stop for any app using this package that is attempting to update to angular 16.

**Comment by xylplm** [comment]
+1. I also urgently need it to be upgraded to support Angular16

**Comment by swapnil0545** [comment]
Any updates? Maybe a PR needs to be raised by community members . Will see if i can also find some time.

**Comment by JFC-TELUS** [comment]
+3
